[2024-03-21T01:00:08.486+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_climate.create_locations_and_forecast_tables scheduled__2024-03-13T00:00:00+00:00 [queued]>
[2024-03-21T01:00:08.490+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_climate.create_locations_and_forecast_tables scheduled__2024-03-13T00:00:00+00:00 [queued]>
[2024-03-21T01:00:08.490+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2024-03-21T01:00:08.496+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_locations_and_forecast_tables> on 2024-03-13 00:00:00+00:00
[2024-03-21T01:00:08.500+0000] {standard_task_runner.py:57} INFO - Started process 234 to run task
[2024-03-21T01:00:08.505+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_climate', 'create_locations_and_forecast_tables', 'scheduled__2024-03-13T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag_climate.py', '--cfg-path', '/tmp/tmplmpiyjhy']
[2024-03-21T01:00:08.506+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask create_locations_and_forecast_tables
[2024-03-21T01:00:08.547+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_climate.create_locations_and_forecast_tables scheduled__2024-03-13T00:00:00+00:00 [running]> on host 50fc123683ca
[2024-03-21T01:00:08.571+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'create_locations_and_forecast_tables', field 'sql'. Template: ['CREATE TABLE IF NOT EXISTS location (\n        id INT PRIMARY KEY,\n        nombre VARCHAR(100)\n    ) DISTSTYLE ALL SORTKEY (id);', 'populate_locations_table.sql', 'CREATE TABLE IF NOT EXISTS forecast (\n        id INT IDENTITY(1,1) PRIMARY KEY,\n        date TIMESTAMP,\n        prediction_date TIMESTAMP,\n        locationId INT REFERENCES location(id),\n        max_temperature FLOAT,\n        min_temperature FLOAT,\n        precipitation_probability_max FLOAT\n    ) DISTKEY (locationId) SORTKEY (date);']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 165, in render_template
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 165, in <listcomp>
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: populate_locations_table.sql
[2024-03-21T01:00:08.572+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 165, in render_template
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 165, in <listcomp>
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: populate_locations_table.sql
[2024-03-21T01:00:08.579+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_climate, task_id=create_locations_and_forecast_tables, execution_date=20240313T000000, start_date=20240321T010008, end_date=20240321T010008
[2024-03-21T01:00:08.583+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task create_locations_and_forecast_tables (populate_locations_table.sql; 234)
[2024-03-21T01:00:08.596+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-03-21T01:00:08.609+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-21T01:19:23.202+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_climate.create_locations_and_forecast_tables scheduled__2024-03-13T00:00:00+00:00 [queued]>
[2024-03-21T01:19:23.208+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_climate.create_locations_and_forecast_tables scheduled__2024-03-13T00:00:00+00:00 [queued]>
[2024-03-21T01:19:23.208+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2024-03-21T01:19:23.221+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_locations_and_forecast_tables> on 2024-03-13 00:00:00+00:00
[2024-03-21T01:19:23.226+0000] {standard_task_runner.py:57} INFO - Started process 1140 to run task
[2024-03-21T01:19:23.229+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_climate', 'create_locations_and_forecast_tables', 'scheduled__2024-03-13T00:00:00+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/dag_climate.py', '--cfg-path', '/tmp/tmpkziepjll']
[2024-03-21T01:19:23.230+0000] {standard_task_runner.py:85} INFO - Job 94: Subtask create_locations_and_forecast_tables
[2024-03-21T01:19:23.270+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_climate.create_locations_and_forecast_tables scheduled__2024-03-13T00:00:00+00:00 [running]> on host 50fc123683ca
[2024-03-21T01:19:23.313+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_climate' AIRFLOW_CTX_TASK_ID='create_locations_and_forecast_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-03-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-13T00:00:00+00:00'
[2024-03-21T01:19:23.315+0000] {sql.py:274} INFO - Executing: ['CREATE TABLE IF NOT EXISTS location (\n        id INT PRIMARY KEY,\n        nombre VARCHAR(100)\n    ) DISTSTYLE ALL SORTKEY (id);', "INSERT INTO location (id, nombre)\n    VALUES\n        (1, 'Buenos Aires'),\n        (2, 'Córdoba'),\n        (3, 'Rosario'),\n        (4, 'Mendoza'),\n        (5, 'San Miguel de Tucumán'),\n        (6, 'La Plata'),\n        (7, 'Mar del Plata'),\n        (8, 'Salta'),\n        (9, 'Santa Fe'),\n        (10, 'San Juan'),\n        (11, 'Resistencia'),\n        (12, 'Santiago del Estero'),\n        (13, 'Posadas'),\n        (14, 'San Salvador de Jujuy'),\n        (15, 'Bahía Blanca'),\n        (16, 'Paraná'),\n        (17, 'Merlo'),\n        (18, 'José C. Paz'),\n        (19, 'Quilmes'),\n        (20, 'Pilar');", 'CREATE TABLE IF NOT EXISTS forecast (\n        id INT IDENTITY(1,1) PRIMARY KEY,\n        date TIMESTAMP,\n        prediction_date TIMESTAMP,\n        locationId INT REFERENCES location(id),\n        max_temperature FLOAT,\n        min_temperature FLOAT,\n        precipitation_probability_max FLOAT\n    ) DISTKEY (locationId) SORTKEY (date);']
[2024-03-21T01:19:23.325+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `coderhouse_connection` isn't defined
[2024-03-21T01:19:23.327+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_climate, task_id=create_locations_and_forecast_tables, execution_date=20240313T000000, start_date=20240321T011923, end_date=20240321T011923
[2024-03-21T01:19:23.332+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 94 for task create_locations_and_forecast_tables (The conn_id `coderhouse_connection` isn't defined; 1140)
[2024-03-21T01:19:23.363+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-03-21T01:19:23.376+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-21T01:21:17.715+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_climate.create_locations_and_forecast_tables scheduled__2024-03-13T00:00:00+00:00 [queued]>
[2024-03-21T01:21:17.722+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_climate.create_locations_and_forecast_tables scheduled__2024-03-13T00:00:00+00:00 [queued]>
[2024-03-21T01:21:17.723+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2024-03-21T01:21:17.743+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_locations_and_forecast_tables> on 2024-03-13 00:00:00+00:00
[2024-03-21T01:21:17.750+0000] {standard_task_runner.py:57} INFO - Started process 1302 to run task
[2024-03-21T01:21:17.760+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_climate', 'create_locations_and_forecast_tables', 'scheduled__2024-03-13T00:00:00+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/dag_climate.py', '--cfg-path', '/tmp/tmpavbu01s7']
[2024-03-21T01:21:17.761+0000] {standard_task_runner.py:85} INFO - Job 126: Subtask create_locations_and_forecast_tables
[2024-03-21T01:21:17.806+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_climate.create_locations_and_forecast_tables scheduled__2024-03-13T00:00:00+00:00 [running]> on host 50fc123683ca
[2024-03-21T01:21:17.867+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_climate' AIRFLOW_CTX_TASK_ID='create_locations_and_forecast_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-03-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-13T00:00:00+00:00'
[2024-03-21T01:21:17.869+0000] {sql.py:274} INFO - Executing: ['CREATE TABLE IF NOT EXISTS location (\n        id INT PRIMARY KEY,\n        nombre VARCHAR(100)\n    ) DISTSTYLE ALL SORTKEY (id);', "INSERT INTO location (id, nombre)\n    VALUES\n        (1, 'Buenos Aires'),\n        (2, 'Córdoba'),\n        (3, 'Rosario'),\n        (4, 'Mendoza'),\n        (5, 'San Miguel de Tucumán'),\n        (6, 'La Plata'),\n        (7, 'Mar del Plata'),\n        (8, 'Salta'),\n        (9, 'Santa Fe'),\n        (10, 'San Juan'),\n        (11, 'Resistencia'),\n        (12, 'Santiago del Estero'),\n        (13, 'Posadas'),\n        (14, 'San Salvador de Jujuy'),\n        (15, 'Bahía Blanca'),\n        (16, 'Paraná'),\n        (17, 'Merlo'),\n        (18, 'José C. Paz'),\n        (19, 'Quilmes'),\n        (20, 'Pilar');", 'CREATE TABLE IF NOT EXISTS forecast (\n        id INT IDENTITY(1,1) PRIMARY KEY,\n        date TIMESTAMP,\n        prediction_date TIMESTAMP,\n        locationId INT REFERENCES location(id),\n        max_temperature FLOAT,\n        min_temperature FLOAT,\n        precipitation_probability_max FLOAT\n    ) DISTKEY (locationId) SORTKEY (date);']
[2024-03-21T01:21:17.875+0000] {base.py:73} INFO - Using connection ID 'coderhouse_connection' for task execution.
[2024-03-21T01:21:17.930+0000] {base.py:73} INFO - Using connection ID 'coderhouse_connection' for task execution.
[2024-03-21T01:21:19.161+0000] {sql.py:418} INFO - Running statement: CREATE TABLE IF NOT EXISTS location (
        id INT PRIMARY KEY,
        nombre VARCHAR(100)
    ) DISTSTYLE ALL SORTKEY (id);, parameters: None
[2024-03-21T01:21:20.047+0000] {sql.py:418} INFO - Running statement: INSERT INTO location (id, nombre)
    VALUES
        (1, 'Buenos Aires'),
        (2, 'Córdoba'),
        (3, 'Rosario'),
        (4, 'Mendoza'),
        (5, 'San Miguel de Tucumán'),
        (6, 'La Plata'),
        (7, 'Mar del Plata'),
        (8, 'Salta'),
        (9, 'Santa Fe'),
        (10, 'San Juan'),
        (11, 'Resistencia'),
        (12, 'Santiago del Estero'),
        (13, 'Posadas'),
        (14, 'San Salvador de Jujuy'),
        (15, 'Bahía Blanca'),
        (16, 'Paraná'),
        (17, 'Merlo'),
        (18, 'José C. Paz'),
        (19, 'Quilmes'),
        (20, 'Pilar');, parameters: None
